### ISSUE TITLE
docker在bridge模式下无法访问外网

### ISSUE THREAD

**Issue by YYiiEt** [project-openwrt/openwrt-latest#13]
设备：树莓派4b，固定lan口ip且关闭dhcp挂在主路由下，其他皆为默认设置。
宿主机可以访问网络，容器在host模式下也可访问网络，但通过bridge却不行。
![Snipaste_2020-02-28_20-26-09](https://user-images.githubusercontent.com/60560292/75550302-9ae6b480-5a6c-11ea-91c5-6e9e1752acda.png)
![Snipaste_2020-02-28_20-29-34](https://user-images.githubusercontent.com/60560292/75550342-afc34800-5a6c-11ea-847e-6bfa3f1e7769.png)
![Snipaste_2020-02-28_20-31-50](https://user-images.githubusercontent.com/60560292/75550348-b3ef6580-5a6c-11ea-86fe-f0a14b7656ab.png)

**Comment by 1715173329** [comment]
请检索在其他OpenWrt版本下是否拥有相同问题

**Comment by YYiiEt** [comment]
在lean的openwrt下有人遇到相同问题，参考：https://www.right.com.cn/forum/thread-1209004-1-1.html

但按照帖子中提供方法
“然后vim /etc/sysctl.conf，添加下列内容：
net.bridge.bridge-nf-call-ip6tables = 1
net.bridge.bridge-nf-call-iptables = 1
net.bridge.bridge-nf-call-arptables = 1
后台修改设置：
Luci>网络>防火墙>转发：接受
Luci>状态>防火墙>重启防火墙
最后ssh执行service dockerd restart”

执行完流程后问题相同
![Snipaste_2020-02-29_09-11-53](https://user-images.githubusercontent.com/60560292/75598517-1aa96900-5ad7-11ea-8cc9-c292b275d891.png)

考虑到问题不普遍，或许是特定的硬件原因吧

**Comment by 1715173329** [comment]
改了sysctl规则，需要执行 `sysctl -p` 使其生效。

**Comment by YYiiEt** [comment]
> 改了sysctl规则，需要执行 `sysctl -p` 使其生效。

感谢解答，不过当时执行过sysctl -p而且重启甚至在编译前添加都无效，已经放弃了
