### ISSUE TITLE
一些小问题

### ISSUE THREAD

**Issue by fuqiang03** [project-openwrt/openwrt-latest#14]
![QQ截图20200319000900](https://user-images.githubusercontent.com/26851715/76981731-f32b1b00-6975-11ea-9c46-afbbaa634618.png)
官方主题对在线用户显示不太兼容,显示的格式和上面的一样
-------------------------------------------------------------------------

_('CPU Info'),         _('Core:') + cpuinfo.cpucore + _('Thread:') + cpuinfo.cputhread + _('Frequency:') + cpuinfo.cpufreq + 'MHz' + _('Temperature:') + cpuinfo.cputemp + _('Centigrade'),

![QQ截图20200319001331](https://user-images.githubusercontent.com/26851715/76982227-8c5a3180-6976-11ea-950a-8aff53a652af.png)

**Comment by 1715173329** [comment]
小问题，影响不大。
