### ISSUE TITLE
ShadowSocksR Plus+无法订阅

### ISSUE THREAD

**Issue by ClayMoreBoy** [project-openwrt/openwrt-latest#15]
SS/SSR/V2/TROJAN订阅URL无法保存

**Comment by 1715173329** [comment]
手动点击“保存并应用”即可

**Comment by ClayMoreBoy** [comment]
都尝试过不行才发 Issues

**Comment by ClayMoreBoy** [comment]
@1715173329

**Comment by 1715173329** [comment]
上图

**Comment by ClayMoreBoy** [comment]
![QQ截图20200325031828](https://user-images.githubusercontent.com/6189207/77467584-36d6c680-6e47-11ea-9102-dd9faa74efb0.png)
只有保存按钮 且f12添加`<input class="cbi-button cbi-button-apply" type="button" value="保存并应用" onclick="cbi_submit(this, 'cbi.apply')" size="0">`
![QQ截图20200325032005](https://user-images.githubusercontent.com/6189207/77467848-a482f280-6e47-11ea-9a1f-0c37b6335247.png)
出现
![QQ图片20200325032119](https://user-images.githubusercontent.com/6189207/77467825-9cc34e00-6e47-11ea-9ab1-c46e2e6b176c.png)

**Comment by 1715173329** [comment]
你会用么。。。
![image](https://user-images.githubusercontent.com/22235437/77471358-14e04280-6e4d-11ea-911a-06f9a6d2c405.png)
看到旁边的加号了没？点了之后才会添加配置

**Comment by ClayMoreBoy** [comment]
加了不能生效

**Comment by 1715173329** [comment]
ssrplus日志贴上来看看

**Comment by ClayMoreBoy** [comment]
[C]: ?
	/usr/share/shadowsocksr/subscribe.lua:23: in main chunk
stack traceback:
/usr/bin/lua: /usr/share/shadowsocksr/subscribe.lua:23: attempt to call method 'get_first' (a nil value)

**Comment by 1715173329** [comment]
> subscribe.lua:23: attempt to call method 'get_first' (a nil value)

仅在latest上面出现么？

**Comment by ClayMoreBoy** [comment]
有人在lede也报过同样的问题
https://github.com/coolsnowwolf/lede/issues/3757
https://github.com/coolsnowwolf/lede/issues/3731

**Comment by 1715173329** [comment]
这个我估计是你订阅问题，把你的问题和订阅链接通过邮箱发送至 coolsnowwolf@gmail.com ，让大雕看看

**Comment by ClayMoreBoy** [comment]
@1715173329 在大雕https://github.com/coolsnowwolf/lede源下编译的固件(SSR+ 173-7)可以订阅
初步解释是否Luci?

**Comment by 1715173329** [comment]
你可以尝试 coolsnowwolf/lede#3757 的方法修改订阅文件
