### ISSUE TITLE
DHCP出现JS错误

### ISSUE THREAD

**Issue by ClayMoreBoy** [project-openwrt/openwrt-latest#16]
![image](https://user-images.githubusercontent.com/6189207/77817950-9fed6100-7109-11ea-8331-980b00dcce7c.png)
SyntaxError
missing ) after argument list
  in http://10.0.0.1/luci-static/resources/view/network/dhcp.js?v=git-19.292.31773-cc35206:?
  at http://10.0.0.1/luci-static/resources/luci.js?v=git-19.292.31773-cc35206:117:16

**Comment by ClayMoreBoy** [comment]
不关内核问题

**Comment by 1715173329** [comment]
用最新commit构建的么

**Comment by ClayMoreBoy** [comment]
今天构建的

**Comment by 1715173329** [comment]
更新下Feeds看看

**Comment by ClayMoreBoy** [comment]
今天云编译又好了
